services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5832:5432"
    environment:
      POSTGRES_USER: ${ORDERS_DATASOURCE_USERNAME:-orders}
      POSTGRES_PASSWORD: ${ORDERS_DATASOURCE_PASSWORD:-aNvXaW3mNM7EQAL2}
      POSTGRES_DB: ${ORDERS_DATASOURCE_DATABASE:-orders-database}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - com.rpe.challenge

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./config/redis/users.acl:/usr/local/etc/redis/users.acl
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always
    networks:
      - com.rpe.challenge

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - DEBUG=${LOCAL_STACK_DEBUG:-0}
      - SERVICES=sqs
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/localstack/init-sqs.sh:/etc/localstack/init/ready.d/init-sqs.sh"
    networks:
      - com.rpe.challenge

volumes:
  postgres-data:
  redis-data:

networks:
  com.rpe.challenge:
    driver: bridge