services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5832:5432"
    environment:
      POSTGRES_USER: ${ORDERS_DATASOURCE_USERNAME:-orders}
      POSTGRES_PASSWORD: ${ORDERS_DATASOURCE_PASSWORD:-aNvXaW3mNM7EQAL2}
      POSTGRES_DB: ${ORDERS_DATASOURCE_DATABASE:-orders-database}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - com.rpe.challenge
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    restart: always
    networks:
      - com.rpe.challenge

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./config/redis/users.acl:/usr/local/etc/redis/users.acl
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: always
    networks:
      - com.rpe.challenge

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - DEBUG=${LOCAL_STACK_DEBUG:-0}
      - SERVICES=sqs
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/localstack/init-sqs.sh:/etc/localstack/init/ready.d/init-sqs.sh"
    networks:
      - com.rpe.challenge

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: challenge
      ME_CONFIG_BASICAUTH_PASSWORD: hYAicDHjNzfV4oEO
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
    networks:
      - com.rpe.challenge
    depends_on:
      - mongo

  orders-service:
    build: 
      context: ./orders-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./orders-service/.env
    environment:
      - ORDERS_DATASOURCE_URL=jdbc:postgresql://postgres:5432/orders-database
      - PAYMENT_PROCESSOR_URL=http://payment-processor:4001
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - REDIS_HOST=redis
    depends_on:
      - redis
      - postgres
      - localstack
    restart: on-failure
    networks:
      - com.rpe.challenge

  payment-processor:
    build: 
      context: ./payment-processor
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - ./payment-processor/.env
    environment:
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - PAYMENT_API_ADDRESS=payment-processor
      - PAYMENT_MONGODB_HOST=mongo
    depends_on:
      - mongo
      - localstack
    restart: on-failure
    networks:
      - com.rpe.challenge

volumes:
  postgres-data:
  mongo-data:
  redis-data:

networks:
  com.rpe.challenge:
    driver: bridge