### General ###
spring.application.name=Challenge
spring.threads.virtual.enabled=true

### Server ###
server.port=${ORDERS_SERVER_PORT}
server.error.include-stacktrace=never
server.error.include-message=never

### Security & Tokens ###
auth.security.jwt.secret=${ORDERS_JWT_SECRET}
auth.security.jwt.expiration-time=${ORDERS_JWT_SECRET_EXPIRATION_TIME}

### Database & Connection ###
spring.sql.init.mode=always
spring.datasource.url=${ORDERS_DATASOURCE_URL}
spring.datasource.username=${ORDERS_DATASOURCE_USERNAME}
spring.datasource.password=${ORDERS_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.pool-name=challenge-pool
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10

### JPA Specific ###
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.connection.url=${spring.datasource.url}
spring.jpa.properties.hibernate.connection.username=${spring.datasource.username}
spring.jpa.properties.hibernate.connection.password=${spring.datasource.password}
spring.jpa.properties.hibernate.connection.isolation=TRANSACTION_REPEATABLE_READ
spring.jpa.properties.hibernate.connection.pool_size=${spring.datasource.hikari.maximum-pool-size}

### Cache ###
app.cache.default-ttl=${DEFAULT_CACHE_TTL}

### Redis ###
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}